name: Publish Plugin Docs

on:
  release:
    types:
      - released

jobs:
 publish-docs:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      # environment created automatically by GitHub
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3  # v6

    - name: Activate Anaconda Environment
      uses: conda-incubator/setup-miniconda@8ee1f361103df19b6f8c8655fd3967a8ecb162d5  # v4.0.1
      with:
        miniforge-version: latest
        environment-file: environment_unversioned.yml
        activate-environment: ptest
        auto-activate-base: false
      env:
        CONDA_OVERRIDE_ARCHSPEC: x86_64_v4

    - name: Build HTML
      shell: bash -l {0}
      run: |
        sphinx-build -M html user_guide/source/ user_guide/build/

    - name: Setup Pages
      uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d  # v6.0.0

    - name: Upload Artifact
      uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9  #v5.0.0
      with:
        path: "user_guide/build/html/"

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128  # v5.0.0
